# vim:ft=kitty

## name: Molokai
## source: Ghostty built-in theme

color0 #121212
color1 #fa2573
color2 #98e123
color3 #dfd460
color4 #1080d0
color5 #8700ff
color6 #43a8d0
color7 #bbbbbb
color8 #555555
color9 #f6669d
color10 #b1e05f
color11 #fff26d
color12 #00afff
color13 #af87ff
color14 #51ceff
color15 #ffffff
background #121212
foreground #bbbbbb
cursor #bbbbbb
cursor_text_color #ffffff
selection_background #b5d5ff
selection_foreground #000000
