# vim:ft=kitty

## name: Cobalt Next Dark
## source: Ghostty built-in theme

color0 #262f37
color1 #f94967
color2 #8cc98f
color3 #ffc64c
color4 #409dd4
color5 #cba3c7
color6 #37b5b4
color7 #d7deea
color8 #62747f
color9 #e47e8b
color10 #baddbb
color11 #ffdc91
color12 #7ac0eb
color13 #f3ccef
color14 #84e4e3
color15 #ffffff
background #0b1c24
foreground #d7deea
cursor #ffc64c
cursor_text_color #999999
selection_background #37b5b4
selection_foreground #ffffff
