# vim:ft=kitty

## name: Fahrenheit
## source: Ghostty built-in theme

color0 #1d1d1d
color1 #cda074
color2 #9e744d
color3 #fecf75
color4 #7f0e0f
color5 #734c4d
color6 #979797
color7 #ffffce
color8 #404040
color9 #fecea0
color10 #cc734d
color11 #fd9f4d
color12 #cb4a05
color13 #4e739f
color14 #fed04d
color15 #ffffff
background #000000
foreground #ffffce
cursor #bbbbbb
cursor_text_color #ffffff
selection_background #4e739f
selection_foreground #ffffce
