# vim:ft=kitty

## name: Monokai Pro Machine
## source: Ghostty built-in theme

color0 #273136
color1 #ff6d7e
color2 #a2e57b
color3 #ffed72
color4 #ffb270
color5 #baa0f8
color6 #7cd5f1
color7 #f2fffc
color8 #6b7678
color9 #ff6d7e
color10 #a2e57b
color11 #ffed72
color12 #ffb270
color13 #baa0f8
color14 #7cd5f1
color15 #f2fffc
background #273136
foreground #f2fffc
cursor #b8c4c3
cursor_text_color #859190
selection_background #545f62
selection_foreground #f2fffc
